Repository dat-land/dat-desktop, pull requests merged in 2018-11, with the labels that each got.

#552 Fix/react travis
  .travis.yml
  package.json
Labels: Priority: High, Status: Review Needed

#573 Corrected travis-badge location
  README.md
Labels: Type: Documentation

#577 [WIP] FileList View
  app/actions/dat-middleware.js
Labels: Type: Bug

#588 Removing drag-and-drop as it is incompatible with electron 3
  app/index.js
  package.json
Labels: Type: Bug

#582 Performance: prevent re-rendering of icons.
  app/components/app.js
  app/components/sprite.js
  app/index.js
Labels: react

#575 Integration tests
  index.html
  index.js
  package.json
Labels: Priority: High, Type: Maintenance
